# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepull',
            name='pid',
            field=models.IntegerField(blank=True, default=None, verbose_name='下载的pid'),
        ),
        migrations.AlterField(
            model_name='imagepull',
            name='PullStatus',
            field=models.SmallIntegerField(choices=[(0, '下载进行中'), (1, '下载已经完成'), (2, '下载失败')], verbose_name='下载状态'),
        ),
    ]
